### ISSUE TITLE
Overexposed and foggy image

### ISSUE THREAD

**Issue by AdrienHoodie** [rre36/glsl_kappa#10]
**Describe the bug**
Bug causes entire scene to become overexposed and volumetric fog to become extremely thick and bright upon reloading.

**To Reproduce**
Enter game with the shader enabled and reload it (F3+R or any setting change), image should now be overexposed and foggy. 

**Expected behavior**
Image should remain at same exposure and fog clear upon reload.

**Screenshots**
1.12.2:
![image](https://user-images.githubusercontent.com/46287141/50568312-ecd36380-0d1d-11e9-81c6-14429480e1d0.png)
![image](https://user-images.githubusercontent.com/46287141/50568315-f9f05280-0d1d-11e9-846c-0487e86cae17.png)

1.13.2:
![javaw_2018-12-31_12-47-09](https://user-images.githubusercontent.com/46287141/50568270-6ae33a80-0d1d-11e9-8178-20a15c0bcb7e.png)
![javaw_2018-12-31_12-49-33](https://user-images.githubusercontent.com/46287141/50568271-6e76c180-0d1d-11e9-8a1a-6c2ed048bcfe.png)

**Desktop (please complete the following information):**
Operating System: Windows 10
Graphics Card: AMD Radeon RX 580 8G
Graphics Driver Version: 18.12.2
Game Version: 1.13.2, 1.12.2
OF Version: 1.12.2: E2, E3, E4 pre1; 1.13.2: E5, E6 pre2
CPU: AMD Ryzen 3 2200G
RAM: 8G
Any Overlay Software running: AMD ReLive Instant Replay (tested and works without it)

**Additional context**
1.12.2: Loading from Nostalgia shaders will trigger the bug regardless of if shader was reloaded.

**Comment by rre36** [comment]
As of now it seems like this bug get's triggered by using a render resolution setting that is higher than 1x.

**Comment by rre36** [comment]
https://github.com/rre36/GLSL-LegacyShader/wiki/Known-Issues-and-Workarounds
