### ISSUE TITLE
Incorrect rendering of AO/other effects on Linux + AMD (Mesa)

### ISSUE THREAD

**Issue by Lyokanthrope** [rre36/glsl_kappa#23]
**Describe the bug**
Using Kappa_0.9.2:
Fake GI, Ambient Occlusion, and Subsurface scattering (And and any combination of enabling them) tints the world either red, green, or blue. Fake GI removes world textures entirely when used by itself or with AO turned on. 

**To Reproduce**
Use AMD + latest Mesa, try to use the shader pack with any of the above effects toggled on (which I believe they are by default)

**Expected behavior**
Correct rendering of said effects!

**Screenshots**
Fake GI by itself:
![2019-06-29_08 49 19](https://user-images.githubusercontent.com/4756826/60385132-88365e80-9a4b-11e9-8018-2b368f323748.png)
AO by itself:
![2019-06-29_08 49 57](https://user-images.githubusercontent.com/4756826/60385134-8a002200-9a4b-11e9-8a4e-aeb303001d8f.png)
AO + Subsurface scattering:
![2019-06-29_08 50 04](https://user-images.githubusercontent.com/4756826/60385135-8b314f00-9a4b-11e9-9584-f99707e1ecfa.png)
Subsurface scattering by itself: 
![2019-06-29_08 50 12](https://user-images.githubusercontent.com/4756826/60385136-8c627c00-9a4b-11e9-9df1-2c02bd10fc26.png)
All effects enabled:
![2019-06-29_08 50 18](https://user-images.githubusercontent.com/4756826/60385138-8e2c3f80-9a4b-11e9-9ff6-9f8fa687bd89.png)

**Desktop (please complete the following information):**
Operating System: Manaro Linux (Kernel 5.1.14)
Graphics Card: Radeon RX Vega 56 
Graphics Driver Version: Mesa 19.1.1, LLVM 8.0.0
Game Version: 1.14.3
OF Version: OptiFine_1.14.3_HD_U_F1
CPU: AMD Ryzen 5 1600
RAM: 16GB DDR4-2933
Any Overlay Software running: 

**Additional context**
Tried under 1.12.2, thinking it might have been some issue related to block IDs...same problem.
Logs, if it helps:
https://gist.github.com/Lyokanthrope/fbba1dfe549593428f7b45b4297063e4

**Comment by Lyokanthrope** [comment]
Oh, just noticed another weird issue. Sun shadows seem to turn red when looking at them from a distance & oblique angles, and underwater lightshafts notably more green than I think they're supposed to:
![2019-06-29_09 05 34](https://user-images.githubusercontent.com/4756826/60385348-d5b3cb00-9a4d-11e9-8250-436df1395d93.png)
![2019-06-29_09 06 56](https://user-images.githubusercontent.com/4756826/60385350-d8aebb80-9a4d-11e9-87fc-1ff80cfce940.png)

**Comment by rre36** [comment]
hmm, that is extremely odd, i think i'll take a closer look at linux compatibility with kappa, seems like there are some issues lately

**Comment by Lyokanthrope** [comment]
Is there anything I can do to further help diagnose?

**Comment by Lyokanthrope** [comment]
Whoops, another issue: 
![2019-06-29_14 20 15](https://user-images.githubusercontent.com/4756826/60388568-3c9aa980-9a79-11e9-8eb3-37e6c83424af.png)

All stained glass looks like this.

**Comment by rre36** [comment]
hmm, a few things i'd like you to test:
- does this also occur with previous versions (0.9.0 and possibly also 0.8.x)
- unzipping the pack
- does it also happen with vanilla plus (https://github.com/rre36/GLSL-VPlus/releases/download/v1.4.2/VPlus_v1.4.2.zip) , since my packs are sharing a same code base nowadays and vanilla plus has the most "clean" one, so that i know if it is exclusive to kappa or not

**Comment by Lyokanthrope** [comment]
0.9.0 exhibits the same behavior as 0.9.1 and 0.9.2. [0.8.1 fails to compile multiple shaders, here's a log.](https://gist.github.com/Lyokanthrope/a96c9334ed1d3194516f4e69d381f77d)

Unzipping the pack across the different versions exhibits the same behavior as well.

Vanilla Plus renders fine, even with AO enabled.

As for different debug views...
Whiteworld:
![2019-06-30_07 40 41](https://user-images.githubusercontent.com/4756826/60396697-79fb4780-9b0a-11e9-8b96-539f9af39fda.png)
AO only: 
![2019-06-30_07 40 52](https://user-images.githubusercontent.com/4756826/60396703-82ec1900-9b0a-11e9-96cf-89b4d41ae3ad.png)
Direct light only:
![2019-06-30_07 41 03](https://user-images.githubusercontent.com/4756826/60396708-8aabbd80-9b0a-11e9-83ad-c54469f11a55.png)
Indirect light only: 
![2019-06-30_07 41 11](https://user-images.githubusercontent.com/4756826/60396711-913a3500-9b0a-11e9-87c7-2bba53d67a00.png)

**Comment by rre36** [comment]
alright, indirect light looks completely wrong, so something there causes the issue
